# -*- coding: utf-8 -*-
"""movieTheatreBookingSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JHaGg8FrNg50Jc_E7dlMSLwst9fFSPmR
"""

ava_seats = 350
remainingSeats = ava_seats
ticketsSold = 0
totalBookings = 0
rejectedBooking = 0

while True:
  if remainingSeats == 0:
    print("Theatre is Full")
    break

  noOfTickets = int(input("Enter no of tickets (enter 0 to exit): "))
  if noOfTickets == 0:
    break

  if noOfTickets < 1 or noOfTickets > 15:
    print("booking rejected, allowed to book min 1 and max 15 tickets")
    rejectedBooking += 1
    continue

  if noOfTickets > remainingSeats:
    print(f"we have onlly {remainingSeats} tickets for booking")
    rejectedBooking += 1
    continue

  for i in range(noOfTickets):
    age= int(input(f"enter age of person {i+1}"))
    if age < 12:
      print("Oops,age should be greater than 12 for booking..!")
      rejectedBooking += 1
      continue
  print(f"Booking confirmed, you have booked {noOfTickets} successfully")
  totalBookings += 1
  ticketsSold += noOfTickets
  remainingSeats -= noOfTickets

print("Final report:")
print("Total bookings: ", totalBookings)
print("Rejected booking: ", rejectedBooking)
print("Tickets sold: ", ticketsSold)
print("Remaining Seats: ", remainingSeats)