# -*- coding: utf-8 -*-
"""python_basics_pavan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNKkmMyR3yJsecTfwp7I_OSZCKroO_d8
"""

name = "Pavan"
age = 30
height = 5.5
student = "no"
print("name:", name, "| Age: ", age, "| Height", height, "| Student: ", student)

print(f"Name: {name} | Age: {age} | Height: {height} | Student: {student}")

ageInMonths = age * 12
print("Age in months:", ageInMonths)
ageInYears = age * 365
print("Age in Days: ", ageInYears)
remainder = age%7
print("Remainder when divided by 7: ", remainder)
powerTwo = age**2
print("Age raised to the power of 2: ", powerTwo)